"""Streamlit demo for the RAG Document Question-Answering system.

    streamlit run app.py

Upload your own PDFs/text, pick a retrieval strategy, ask a question, and get a
grounded answer with citations + the exact passages it used. A second tab shows
the project's evaluation results.
"""
from __future__ import annotations

import hashlib

import streamlit as st

from src import config, ingest
from src.pipeline import RAGPipeline

st.set_page_config(page_title="RAG Document QA", page_icon="📄", layout="wide")

RETRIEVERS = {
    "Dense (vector)": "dense",
    "BM25 (keyword)": "bm25",
    "Hybrid (dense + BM25)": "hybrid",
    "Hybrid + cross-encoder re-rank": "rerank",
}


@st.cache_resource(show_spinner="Building index (chunk → embed → store)…")
def build_pipeline(file_sig: str, embedding_model: str, chunk_size: int, _docs: list[dict]):
    """Index the uploaded documents. Cached on (files, model, chunk_size)."""
    pipe = RAGPipeline(
        collection_name=f"streamlit_{file_sig[:8]}",
        embedding_model=embedding_model,
        chunk_size=chunk_size,
        reset=True,
    )
    n_chunks = pipe.index_documents(_docs, show_progress=False)
    return pipe, n_chunks


def _read_uploads(uploaded) -> list[dict]:
    docs = []
    for uf in uploaded:
        name = uf.name
        data = uf.read()
        try:
            text = ingest.read_pdf_bytes(data) if name.lower().endswith(".pdf") \
                else data.decode("utf-8", errors="ignore")
        except Exception as exc:  # noqa: BLE001
            st.warning(f"Could not read {name}: {exc}")
            continue
        if text.strip():
            docs.append({"doc_id": name, "title": name, "text": text})
    return docs


def qa_tab():
    st.sidebar.header("⚙️ Settings")
    embedding_model = st.sidebar.selectbox("Embedding model", config.EMBEDDING_MODELS_TO_COMPARE, index=len(config.EMBEDDING_MODELS_TO_COMPARE) - 1)
    chunk_size = st.sidebar.slider("Chunk size (words)", 128, 1024, config.CHUNK_SIZE, step=128)
    retriever_label = st.sidebar.selectbox("Retrieval strategy", list(RETRIEVERS))
    top_k = st.sidebar.slider("Top-k passages", 1, 10, config.TOP_K)

    has_key = bool(config.GOOGLE_API_KEY) and config.GOOGLE_API_KEY != "your_gemini_api_key_here"
    if not has_key:
        st.sidebar.warning("No Gemini API key found in .env — retrieval works, but answer generation is disabled.")

    st.subheader("1) Upload documents")
    uploaded = st.file_uploader("PDF / TXT / MD (one or more)", type=["pdf", "txt", "md"], accept_multiple_files=True)
    if not uploaded:
        st.info("⬆️ Upload at least one document to begin. The system will retrieve from these and ground every answer in them.")
        return

    docs = _read_uploads(uploaded)
    if not docs:
        return
    file_sig = hashlib.md5(("".join(sorted(d["doc_id"] for d in docs)) + str(chunk_size) + embedding_model).encode()).hexdigest()
    pipe, n_chunks = build_pipeline(file_sig, embedding_model, chunk_size, docs)
    st.success(f"Indexed {len(docs)} document(s) into {n_chunks} chunks.")

    st.subheader("2) Ask a question")
    question = st.text_input("Your question", placeholder="What is the main contribution of this document?")
    if not question:
        return

    pipe.set_retriever(RETRIEVERS[retriever_label])
    with st.spinner("Retrieving…"):
        chunks = pipe.retriever.retrieve(question, k=top_k)

    col1, col2 = st.columns([3, 2])
    with col1:
        st.markdown("### Answer")
        if has_key:
            try:
                from src.generate import generate_answer
                with st.spinner("Generating grounded answer…"):
                    gen = generate_answer(question, [c.text for c in chunks])
                st.write(gen.answer or "_(empty response)_")
            except Exception as exc:  # noqa: BLE001
                msg = str(exc)
                if "RESOURCE_EXHAUSTED" in msg or "429" in msg:
                    st.error("Gemini free-tier quota is exhausted for now (≈20 requests/day). "
                             "Retrieved passages are shown on the right — try again later.")
                else:
                    st.error(f"Generation failed: {msg[:300]}")
        else:
            st.info("Add a Gemini API key to .env to enable grounded answer generation.")

    with col2:
        st.markdown("### Retrieved passages")
        st.caption(f"via **{retriever_label}** · top-{top_k}")
        for i, c in enumerate(chunks, 1):
            with st.expander(f"[{i}] {c.doc_id} · score={c.score:.3f}"):
                st.write(c.text[:1200] + ("…" if len(c.text) > 1200 else ""))


def results_tab():
    st.subheader("Project evaluation results")
    st.caption("Generated by `run_experiments.py` / `evaluate_baseline.py` — see results/figures/.")
    figs = sorted(config.FIGURES_DIR.glob("*.png"))
    if not figs:
        st.info("No figures yet. Run `python run_experiments.py --skip-answers` to generate them.")
        return
    for path in figs:
        st.image(str(path), caption=path.name, width=560)


def main():
    st.title("📄 Document Question Answering (RAG)")
    st.caption("Retrieval-Augmented Generation · Sentence-Transformers + ChromaDB + Gemini")
    tab_qa, tab_results = st.tabs(["💬 Ask", "📊 Evaluation results"])
    with tab_qa:
        qa_tab()
    with tab_results:
        results_tab()


if __name__ == "__main__":
    main()
